week0/frozenlake.ipynb

* Make code more PEP8-compliant through adding missing spaces after semicolons.
E.g. "def foo(a,b): ..." -> "foo(a, b): ...".
* Complete Python 2 <-> Python 3 compatibility transition by adding
missing parenthesis in several "print" function calls.

Perform minor code cleanup.

---

week2_value_based/seminar1_VI.ipynb

- `get_new_vpi` renamed to `compute_vpi` in test
- removed `:param state_values:` from docstring for `compute_vpi` function.

fix/rename get_new_vpi  to porper name in tests

---

week4_approx_rl/homework_tf.ipynb

function 'load_weigths_into_target_network' create the  'assigns' tensor operators repeatedly when the function is called. These tensors are not gabage collected and bloats the memory along training.

Fix:  memory bloating when training

---

grading.py

Currently the version that is already deployed on Coursera contains this change. This PR brings it into the branch officially.
Note: this change was introduced before I started working on the project, so I would like to request review from people who are familiar with the reason for this change.

Change submission URL to the one that is already deployed

---

week02_value_based/mdp.py

Reverts yandexdataschool/Practical_RL#128
Function "weighted_choice" still expects list and your pass integer. Probably you had not commited all the changes. I will revert this commit for now.

Revert "Fix inconsistent get_action_value and np.random.choice usage"

---

week04_[recap]_deep_learning/notmnist.py

wget is installed more often than curl
For example, in the course docker container curl is not installed but wget is installed

week04_[recap]: curl -> wget

---

week2_model_based/practice_vi.ipynb
week2_model_based/submit.py

As reported [on the forums](https://www.coursera.org/learn/practical-rl/discussions/all/threads/810KlEVyEemjVAr-CnpblA), the tests are currently non-deterministic and thus can fail randomly. This PR fixes two instances of that.
Please note that a similar fix has already been applied to the the [seminar notebook](https://github.com/yandexdataschool/Practical_RL/blob/spring19/week02_value_based/seminar_vi.ipynb) from week 2.
_Probably_ also fixes #144.

Fix nondeterministic behavior in tests

---

grading.py

There are [reports](https://www.coursera.org/learn/practical-rl/discussions/all/threads/JlrtzUtUEemNRw61-ZGN9A) on the forum that seem to indicate that Coursera response may contain `None` in `d['details']`. This PR just dumps the whole `response.json()` entirely whenever Coursera does not respond with HTTP 201.

Improve Coursera submission error reporting

---

week3_model_free/qlearning.ipynb
week3_model_free/submit.py

In #89, a fix was suggested for week3 submission. This fix was implemented and made two functions obsolete. This PR deletes these functions and renames a combined function (which was made default in `c5a6228`) from `submit_qlearning_all()` to just `submit_qlearning()`.

Remove redundant submission functions

---

week06_policy_based/a2c-optional.ipynb

Correct key for `trajectory['state']` in  "runners.py"  is ` 'latest_observation'`

fixed typo  'latest_observations'

---

week4_approx/submit.py

`generate_session()` returns a single number (the total reward), not a triple, unlike in previous weeks.
Fixes #187.

Fix submission script (#187)

---

week01_intro/pong.py
week02_value_based/mdp.py
week04_[recap]_deep_learning/mnist.py
week04_[recap]_deep_learning/notmnist.py
week04_approx_rl/atari_wrappers.py
week04_approx_rl/framebuffer.py
week04_approx_rl/replay_buffer.py
week04_approx_rl/utils.py
week05_explore/bayes.py
week06_policy_based/atari_wrappers.py
week06_policy_based/env_batch.py
week06_policy_based/runners.py
week07_seq2seq/basic_model_tf.py
week07_seq2seq/basic_model_theano.py
week07_seq2seq/basic_model_torch.py
week07_seq2seq/voc.py
week08_pomdp/atari_util.py
week08_pomdp/env_pool.py
week09_policy_II/mujoco_wrappers.py

I ran `autopep8 -i -a -a -a -r .` in the repo root and fixed manually everything I found unsatisfactory.
The diff is best viewed with the "ignore whitespace changes" option.

Apply autopep8 to all Python 3 scripts

---

week01_intro/crossentropy_method.ipynb

Using `warm_start` in conjunction with `max_iter=1` may result in the following error during a call to `fit()`:
```
ValueError: warm_start can only be used where `y` has the same classes as in the previous call to fit. Previously got [0 1], `y` has [0]
```
This is due to a certain peculiarity in `fit()` implementation which only arises if `y` happens to contain only one class by chance. `partial_fit()` is not affected by it, and, in fact, it is a superior option in terms of code cleanliness anyway.
Originally reported at the [Coursera forum](https://www.coursera.org/learn/practical-rl/discussions/all/threads/VNQ59ldoEeiTLBKb9DFnUA).

Prevent warm_start same classes error

---

week02_value_based/seminar_vi.ipynb

Fixes #242.
Also replaces `allclose` with a more semantically appropriate `isclose`.
Tested it and it works with my implementation of all `YOUR CODE HERE` blocks.

Fix tests after changing MDP structure

---

week04_[recap]_deep_learning/practice_tensorflow.ipynb
week04_approx_rl/homework_lasagne.ipynb
week08_pomdp/practice_tensorflow.ipynb
week09_policy_II/seminar_TRPO_pytorch.ipynb
week09_policy_II/seminar_TRPO_tensorflow.ipynb
week09_policy_II/seminar_TRPO_theano.ipynb

Postimg has moved (see e.g. https://meta.stackexchange.com/questions/310325/should-we-fix-postimg-org-links-to-postimg-cc).

Replace image links from postimg.org to postimg.cc

---

week1_intro/crossentropy_method.ipynb
week1_intro/deep_crossentropy_method.ipynb
week1_intro/gym_interface.ipynb
week3_model_free/experience_replay.ipynb
week3_model_free/qlearning.ipynb
week3_model_free/sarsa.ipynb
week4_approx/dqn_atari.ipynb
week4_approx/practice_approx_qlearning.ipynb
week5_policy_based/practice_a3c.ipynb
week5_policy_based/practice_reinforce.ipynb
week6_outro/practice_mcts.ipynb

This ensures that future attempts to autoformat the code won't break it again.
Complementary to #283.

Replace %env magic with os.environ

---

week09_policy_II/ppo.ipynb

Fix formulas in PPO hw

---

week01_intro/crossentropy_method.ipynb

Fix TaxiV2 env to TaxiV3.
New gym version will throw exception
`DeprecatedEnv: Env Taxi-v2 not found (valid versions include ['Taxi-v3'])`
> 2019-08-23 (v0.15.2)
> Taxi-v2 -> Taxi-v3 (add missing wall in the map to replicate env as describe in the original paper, thanks @kobotics) (https://github.com/openai/gym/blob/064a53ae65bbacf5f3ce1718e887b28ab84694d6/README.rst)

Change Taxi-v2 to Taxi-v3

---

week5_policy_based/practice_reinforce.ipynb
week5_policy_based/submit.py

This is a fix for the bug reported in https://www.coursera.org/learn/practical-rl/discussions/all/threads/f1Q1d1RREemEwgpK0w-bBg/replies/C2ule8BMRPGrpXvATKTxOw/comments/GPDOqhjLTsCwzqoYyz7AjA .
Basically, the line
```
env = gym.wrappers.Monitor(gym.make("CartPole-v0"), directory="videos", force=True)
```
used to overwrite the `env` which was used in `generate_session()`, capping the time limit at 200.

[week5] Fix accidental TimeLimit in CartPole

---

week6_outro/bandits.ipynb

https://www.coursera.org/learn/practical-rl/discussions/all/threads/5q3UJBDfQ8yt1CQQ3xPMzA reports that we shouldn't have removed the `get_regret()` function as part of https://github.com/yandexdataschool/Practical_RL/pull/292 as it is needed for submission.

[week6] Fix missing get_regret() function

---

week1_intro/deep_crossentropy_method.ipynb
week1_intro/submit.py

This is kinda embarassing. We have been telling students that the interface of `generate_session_mountain_car()` was identical to the interface of `generate_session()`, but it actually wasn't.

[Week 1] Fix interface for generate_session() in deep CEM

---

week01_intro/primer_python_for_ml/recap_ml.ipynb

The following typos were fixed:
1. In Part III, there were spaces between `%%` and `time` in the second and third examples of using `%%time`. Those spaces were removed.
2. In Part III, in the example of selecting all elements in a that are even, an incorrect string was being printed.
The following logic error was fixed:
1. In Part III, in the example that found the person who paid the most `data.loc` was incorrectly being used instead of `data.iloc`.

Fix typos and logic errors in recap_ml.ipynb

---

week06_policy_based/a2c-optional.ipynb
week06_policy_based/atari_wrappers.py

Previously only TFSummaries was supported.
Those who wanted to use Pytorch, had to implement summaries method by
themselves (to get total reward).
Now NumpySummaries class is added. It allows to get summaries without
tensorflow.
In the notebook it's set to default now.

Add NumpySummaries class

---

week07_seq2seq/practice_tf.ipynb

As reported in https://www.coursera.org/learn/practical-rl/discussions/all/threads/4F_UVY3bTGif1FWN25xodg, `model.translate()` does not exist. The corresponding cell was removed in the PyTorch version of the notebook, so I am also removing it here.

[Week 7] Avoid AttributeError on TF BasicTranslationModel

---

week6_outro/seq2seq/practice_tf.ipynb

As reported in https://www.coursera.org/learn/practical-rl/discussions/all/threads/4F_UVY3bTGif1FWN25xodg, `model.translate()` does not exist. The corresponding cell was removed in the PyTorch version of the notebook, so I am also removing it here.

[Week 6] Avoid AttributeError on TF BasicTranslationModel

---

week01_intro/crossentropy_method.ipynb
week02_value_based/seminar_vi.ipynb
week03_model_free/homework.ipynb
week03_model_free/seminar_qlearning.ipynb
week04_[recap]_deep_learning/practice_tensorflow.ipynb
week04_[recap]_deep_learning/seminar_pytorch.ipynb
week04_approx_rl/homework_pytorch_debug.ipynb
week04_approx_rl/homework_pytorch_main.ipynb
week04_approx_rl/seminar_pytorch.ipynb
week06_policy_based/reinforce_lasagne.ipynb
week07_[recap]_rnn/seminar_pytorch.ipynb
week07_seq2seq/bonus_pytorch.ipynb
week08_pomdp/homework_common_part2.ipynb
week08_pomdp/practice_tensorflow.ipynb
week09_policy_II/seminar_TRPO_pytorch.ipynb
week09_policy_II/seminar_TRPO_theano.ipynb

There are two commits. The first one fixes the JSON for three notebooks from Week 4 and Week 7 Recap:
```
week04_approx_rl/homework_pytorch_debug.ipynb
week04_approx_rl/homework_pytorch_main.ipynb
week07_[recap]_rnn/seminar_pytorch.ipynb
```
They had very large diff when I attempted to fix Colab setup in #336.
The second commit cleans up metadata in all notebooks using my (now standard) script:
```python
#!/usr/bin/env python3
import argparse
import sys
import subprocess
from pathlib import Path
parser = argparse.ArgumentParser()
parser.add_argument('path', type=Path)
parser.add_argument('--clear-outputs', action='store_true', help='Clear outputs of all cells')
args = parser.parse_args()
jq_cmd = [
'(.cells[] | select(has("execution_count")) | .execution_count) = null',
'.metadata = …
```

Cleanup JSON in notebooks

---

week06_policy_based/reinforce_pytorch.ipynb

Almost none of students use no_grad in their homeworks (they use detach/data instead).

[Week 6] seminar pytorch: Add no_grad hint

---

week1_intro/crossentropy_method.ipynb
week3_model_free/experience_replay.ipynb
week3_model_free/qlearning.ipynb

`Taxi-v3` doesn't work with `gym==0.14.0`.

Revert Taxi-v3 to v2 because gym in Coursera is too old

---

week07_seq2seq/voc.py

From launch to launch the jupyter notebook, one can notice, that Vocab.token_to_ix differs. It is due to randomness in Vocab.from_lines, in which tokens are stored in set, and elements order in set is undefined.
The fix is to store tokens in list in sorted way.

Week 07 get rid of randomness of Vocab.from_lines

---

week04_[recap]_deep_learning/seminar_tensorflow.ipynb
week04_approx_rl/homework_tf.ipynb
week04_approx_rl/seminar_tf.ipynb
week06_policy_based/reinforce_tensorflow.ipynb
week07_seq2seq/practice_tf.ipynb

With the extra check, `%tensorflow_version 1.x` is not called on kernel restarts.

Fix redundant .setup_complete check

---

week07_seq2seq/bonus_pytorch.ipynb

Some context:
One of the students sent a homework with wrong logic in Attention:
He multiplies attention weights by their own logits (instead of multiplying encoder sequence by attention weights).
I said him about his error. But he said that such logic had beed described in the course notebook.
I have checked it and turns out that:
1. There was the original bonus.ipynb with correct description and class draft;
2. Then one of the students created bonus_pytorch.ipynb with wrong description and his PR was merged.
Now, as most of the students use pytorch, they can see wrong description and write wrong code.
Here we fix the description.

[Week7 seq2seq] Fix wrong description of attention in week7 in bonus_pytorch.ipynb

---

week06_policy_based/local_setup.sh
week06_policy_based/reinforce_tensorflow.ipynb

1) I took out the installation of some dependencies into a separate file
2) rewrote the task in tf2
3) fixed some bugs in the previous version
4) tested with my own solution to the home task

Upgrade week 6 reinforce homework to tf 2

---

week06_policy_based/a2c-optional.ipynb
week06_policy_based/atari_wrappers.py

1) There were 2 functions in the class TFSummary, they used tf1 API, I replaced them with corresponding functions from tf2 API (both are referenced here https://www.tensorflow.org/api_docs/python/tf/summary/scalar).
2) There was unnecessary import in the add_summary_scalar function. Tensorflow has to be imported by the time this method is called cause importing is in the constructor of the TFSummary class.
3) There was no alternative in natrure_dqn to use NumPy summary even if a corresponding argument is set into a corresponding state -- bug fix.
4) Different style of putting (or not putting) spaces between an argument name and its value in a function call in one file -- code style fix

Upgrade atari_wrapper to tf2

---

week04_approx_rl/seminar_tf.ipynb

https://www.coursera.org/learn/practical-rl/discussions/all/threads/RRaAuhCbEeuoKgpcLmLqdw
I guess that either TF or Keras broke backwards compatibility, and `__call__()` no longer accepts Numpy tensors, contrary to what is said in https://stackoverflow.com/a/60871692.
We introduced this here: https://github.com/yandexdataschool/Practical_RL/pull/448/files#diff-61c5d5737d7f6d9831dd0d962e3e4feee9bc47dd25924cd56b16d8c499e3a43dR126

Revert part of https://github.com/yandexdataschool/Practical_RL/pull/448

---

week02_value_based/mdp.py

How to reproduce the errors:
```
env = MDP(
transition_probs={'AndroidHell': {'wait': None}},
rewards={'AndroidHell': {'wait': -1}})
```
Expected error: `AssertionError: transition_probs for AndroidHell should be a a dictionary but is instead <class 'NoneType'>`
Observer error: `KeyError: ('AndroidHell', 'wait')`
```
env = MDP(
{
'AndroidHell': {'wait': {'AndroidHell': 1}},
'EnrichmentCenter': {'testing': {'EnrichmentCenter': 0.95, 'AndroidHell': 0.05}}
},
{
'AndroidHell': {'wait': {'AndroidHell': -1}},
'EnrichmentCenter': None
})
```
Expected error: `AssertionError: rewards for EnrichmentCenter should be a dictionary but is instead <class 'NoneType'>`
Observed error: `AssertionError: rewards for EnrichmentCenter should be a dictionary but is instead <class 'dict'>` if the previous error …

Fixed errors in assertion messages

---

week04_approx_rl/homework_pytorch_main.ipynb

Previously: if one changed variable REPLAY_BUFFER_SIZE to 10^5 code would create a buffer of size 10^5, but only 10*^4 games would be played and recorded.
That could lead to time losses.

Replace constants with variables

---

week05_explore/week5.ipynb

В [numpy иная параметризация](https://numpy.org/doc/stable/reference/random/generated/numpy.random.gamma.html) бета-распределения - не `alpha, beta` (`shape, rate`), а `k, theta` (`shape, scale`), на [википедии](https://en.wikipedia.org/wiki/Gamma_distribution) можно увидеть обе. [Связь](https://en.wikipedia.org/wiki/Gamma_distribution#Characterization_using_shape_%CE%B1_and_rate_%CE%B2) между ними - `scale = 1 / rate`.
Хотя это почти не влияет на то, как обучается модель в задании.

Fix numpy beta distribution arguments

---

week04_approx_rl/homework_pytorch_main.ipynb

Hey! I just thought this change might be helpful! Just for a better understanding of what time I can stop my long learning and be on the same scale as the graph and `final_score` variable. 
Because right now, for some reason, we're doing the following:
```python3
final_score = evaluate(
make_env(clip_rewards=False, seed=9),
agent, n_games=30, greedy=True, t_max=10 * 1000
) * 5
assert final_score >= 15, "not as cool as DQN can"
```
Suggestion:
```python3
final_score = evaluate(
make_env(clip_rewards=False, seed=9),
agent, n_games=30, greedy=True, t_max=10 * 1000
)
assert final_score >= 3, "not as cool as DQN can"
```
What do you think?
Also, I faced with this [problem](https://github.com/openai/atari-py/issues/83), and added [this](https://github.com/openai/atari-py/issues/83#issuecomment-8 …

Week04 suggestion

---

week06_policy_based/atari_wrappers.py

Multiprocessing in Python works differently on Windows and on Linux. On Windows it copies the objects and in Linux it doesn't. As a result, some code that works fine on Linux may not work on Windows. E.g. in our A2C homework we use lambda functions.
Lambda functions are not serializable, so object copying during multiprocessing would fail on Windows. As for MacOS, it can behave like Linux or like Windows depending on settings.
In this commit I added an instruction that will make the multiprocessing behave like Linux

Support MacOS in A2C homework multiprocessing

---

week01_intro/crossentropy_method.ipynb

np.float is deprecated in a current version of numpy
The next best guess is that this variable will be of type np.float64

fix: fix np float for current numpy version

---

week02_value_based/mdp.py

In Google Colab charts with `plot_graph()` fail to render correctly. All the time it is cut from one side or another
When `graph_size` removed everything works just fine

Remove `graph_size` argument from plot_graph()

---

week09_policy_II/README.md

Fix broken link to youtube video at section `More: Reinforcement learning in large/continuous action spaces` - `Lecture by A. Seleznev, 5vision (russian)`. Also mentioned at [Broken links](https://github.com/yandexdataschool/Practical_RL/issues/84) issue

Fix broken link to at `week09_policy_II`
