Amazon GPU howto.md

Запилил небольшой мануал о том как поднять тачку с GPU в EC2 облаке

Мануал по амазону

---

docker/README.md
docker/run_jupyter.sh

Fixed problems with native docker launch

changed docker env

---

week4_approx_rl/framebuffer.py
week4_approx_rl/homework_pytorch.ipynb

Also fixed tests for the Preprocessing Atari class (make it work with Python 3 and fix imshow call).
Added more understandable "Here is what the network gonna see" picture (with a ball).

Fixed framebuffer for PyTorch homework.

---

week3_model_free/homework/homework.ipynb

update parameters in Agent constructors and print for python 3.

Agent Constructors

---

week4_approx_rl/seminar_pytorch.ipynb

Add env.close()

---

week2_value_based/seminar2_MCTS.ipynb

Wrongly named env as far as I can see

Refer to Acrobot instead of AcroBot

---

docker/README.md

Typo in README.md

---

week4_approx/practice_approx_qlearning.ipynb

This makes it work in the notebook server hosted by Coursera. Otherwise it crashes with the TensorFlow and Keras versions that are currently installed on the notebook server.

use keras.backend.placeholder instead of tf.placeholder

---

week3_model_free/submit.py

I see this problem when I tried to submit my first assignment in week3. This should fix it.

Fix idendation error

---

README.md

Corrected the spelling of several in contributions section of README.md

fixed a typo in the contributions section of README.md

---

docker/README.md

- Add `--rm` option to automatically remove the docker container after running
- Modify the example command to use user's current directory
- Don't specify the CMD for docker, since it's already specifiedy in Dockerfile

Improve Docker README.md

---

week3_model_free/submit.py

https://www.coursera.org/learn/practical-rl/discussions/all/threads/nWjR3_h-Eei8_xIX6YqsyA

Fix spaces in week3_model_free/submit.py

---

week5_policy_based/practice_a3c.ipynb

`evaluate()` now divides `total_reward` by `reward_scale`.
Also (automatically) prettify some cells.
Fixes https://github.com/yandexdataschool/Practical_RL/issues/109.

Fix reward scaling

---

week02_value_based/mdp.py
week02_value_based/seminar_vi.ipynb

See the commits description for the details

 Fix the optimal strategy visualisation in Week 2

---

week02_value_based/mdp.py

The problem and another way to solve is described in #119

week2, mdp viz: lightgreen is not a known color

---

xvfb

* Make it executable
* Add shebang
* Improve formatting

Improve xvfb script

---

grading.py

Report: https://www.coursera.org/learn/practical-rl/discussions/all/threads/nWjR3_h-Eei8_xIX6YqsyA/replies/iViyAPxzEeisMwqjNj3fCg/comments/l6siajAHEem01ApI08KErg

Do not crash if Coursera response cannot be parsed as JSON

---

week02_value_based/mdp.py

Hey guys, 
Had to make these changes to make week 2 notebook work end to end. I'm kind of new to Python, so not 100% sure it's "the right" way. But all notebook tests pass and Coursera grader is happy.

Fix inconsistent get_action_value and np.random.choice usage

---

week2_model_based/mdp.py

[week2] Fix incorrect usage of np.random.choice

---

week01_intro/crossentropy_method.ipynb

1.1 (1 pts) Find out how the algorithm performance changes if you change different percentile and different n_samples. 
Did you mean n_sessions?

Change n_samples to n_sessions

---

week04_[recap]_deep_learning/seminar_pytorch.ipynb

Task II correction. Life game
scipy convolution referred does not work properly
demonstaration on lines 1000 - 1050

week04_[recap]_deep_learning.ipynb

---

week04_approx_rl/homework_pytorch_debug.ipynb
week04_approx_rl/homework_pytorch_main.ipynb

total_steps == 3 * 10^6 -> last step in "for" cycle == 3 * 10^6 - 1
eval_freq == 5000
(3 * 10^6 - 1) % 5000 != 0 -> after last 4999 iterations agent is not evaluated

week04: prevented training time losing

---

week05_explore/week5.ipynb

Not just small mistake but the reason of an exception

week05: [T/t]ompson -> [T/t]hompson, epsilin -> epsilon

---

week2_model_based/mdp.py

https://www.coursera.org/learn/practical-rl/discussions/all/threads/cIS-FD8DEem8VAoMgvO9qg

Use len() on possible_states which is a tuple

---

week07_seq2seq/basic_model_torch.py

Changed tensor type transformations to minimal dtype transformations.
Model now compatible with any device. "to_one_hot" returns tensor of the
same device as input. Removed deprecated Variables.

device compatible, removed Variable

---

grading.py
week2_model_based/practice_vi.ipynb
week2_model_based/submit.py

Multiple fixes. Please refer to the list of commits for more details. The diff is better viewed with [`?w=1`](https://github.com/yandexdataschool/Practical_RL/pull/185/files?w=1).
This is a draft PR b/c I haven't tested it yet.

Coursera fixes

---

week1_intro/deep_crossentropy_method.ipynb

* Clean all outputs
* Fix broken link to `digging_deper_final.jpg`
* Split notebook into two parts: Practice and Assignment
* Reformat code, cleanup redundant empty lines, fix comment formatting
* Ensure that all headers follow a hierarchical structure
* Remove all references to LunarLander as we do not support it in submission anyway
* Rename function in the bottom cell from `generate_session` to `generate_session_mountain_car` to avoid confusion (fixes #157)

cousera/week1/deep_cem: clarify assignment & cleanup notebook

---

week07_seq2seq/practice_torch.ipynb

Fixes #175. Also cleans up metadata.

Fix im2latex link (#175)

---

week05_explore/week5.ipynb
week10_planning/seminar_MCTS.ipynb

Minor bugs from 6 coursera week.

Backport coursera/week6 modifications to spring19

---

xvfb

* Make it executable
* Add shebang
* Improve formatting
* Move pidfile to $XDG_RUNTIME_DIR
Fixes #143.

Improve xvfb script (#143)

---

week04_approx_rl/seminar_tf.ipynb

Some stuff related to coursera bugs, but why not?

Backport coursera/week4 modifications to spring19

---

week06_policy_based/reinforce_tensorflow.ipynb

Some explanations from coursera version added, output cleared.

Backport coursera/week5 modifications to spring19

---

week02_value_based/seminar_vi.ipynb

There used to be a mismatch between the definition and the illustration.
This PR might be incomplete as there might be assertions dependent on the MDP structure. I haven't tested it entirely, nor have I looked into whether there are any such tests in the Coursera grader.

Fix MDP definition and change illustration to SVG

---

week1_intro/crossentropy_method.ipynb
week1_intro/deep_crossentropy_method.ipynb

PEP8 fixes and visualize_mountain_car added

Week01 fixes from YSDA to Coursera branch

---

docker/README.md

A slightly more novice-proof instruction to fix misunderstanding from
https://www.coursera.org/learn/practical-rl/discussions/all/threads/E6IkT54xEemB7BKA79O1vg
(i mistakenly changed it in the wrong branch)

adress coursera docker complaint

---

week5_policy_based/practice_reinforce.ipynb

Week 5 changes to Coursera + issue #121 fixed

---

week01_intro/crossentropy_method.ipynb
week01_intro/deep_crossentropy_method.ipynb

Первый ноутбук - табличный CEM
Второй ноутбук - нейронки и ДЗ (которое нужно отпилить при переходе в ШАД)
Sanity check: хочется чтобы текст ДЗ можно было поменять и не сломать курсеру.

split CEM notebook in two

---

deployment.md

The purpose of this PR is to bring your attention to this update. Coursera have (finally!) allowed to access internet from within containers. I have verified that these instructions work and I will merge the PR myself in a couple of days (unless there are strong reasons not to).

Update instructions now that internet works within containers

---

week1_intro/gym_interface.ipynb

Issue reported at https://www.coursera.org/learn/practical-rl/discussions/all/threads/nWf2omi7EemTWxL_dp7UIA.
Not sure how it did not get included in https://github.com/yandexdataschool/Practical_RL/pull/235.
Merging it myself as it is trivial and urgent.

Fix missing env.reset()

---

week2_model_based/mdp.py
week2_model_based/practice_vi.ipynb

Visualisation added and mdp fixed

Week02 changes to Coursera branch

---

week07_seq2seq/basic_model_tf.py

Remove unused states_seq

---

week1_intro/primer/recap_tensorflow.ipynb

Change Tensorboard port 6000 -> 7007 and logdir ./tboard -> /tmp/tboard

---

week2_model_based/mdp.py
week2_model_based/submit.py

Fix nondeterminism in Week 2 assignment

---

week02_value_based/mdp.py

Backports https://github.com/yandexdataschool/Practical_RL/pull/266.

Backport determinism fixes from coursera to master

---

week6_outro/seq2seq/practice_tf.ipynb
week6_outro/seq2seq/submit.py

Resolves #263.
The corresponding grader is [here](https://www.coursera.org/teach/practical-rl/content/edit/programming/pk6i2?versionId=Ni9w_INfEeetQwoqGsZceA).

Implement Coursera grader for week6/seq2seq

---

week1_intro/gym_interface.ipynb
week3_model_free/experience_replay.ipynb
week3_model_free/qlearning.ipynb
week3_model_free/sarsa.ipynb
week4_approx/dqn_atari.ipynb
week4_approx/practice_approx_qlearning.ipynb
week5_policy_based/practice_a3c.ipynb
week6_outro/practice_mcts.ipynb

I especially like the code that we had in weeks 4 and 5.

Unify missing display check

---

youtube_dl_lectures.sh

The majority is courtesy of https://github.com/shpotes/Practical_RL/commit/1bd4e456a6c84e1aa29a9f5fa419653f6840293c

Update paths and cleanup youtube-dl script

---

week4_approx/dqn_atari.ipynb

Fix Python 2 print style

---

week5_policy_based/atari_util.py

Fix double normalization of images

---

week1_intro/primer/recap_ml.ipynb

ML primer to Coursera branch

---

week06_policy_based/reinforce_tensorflow.ipynb

Port of https://github.com/yandexdataschool/Practical_RL/pull/315 to `master`.

[week6] Fix accidental TimeLimit in CartPole

---

week03_model_free/README.md
week03_model_free/homework.ipynb
week03_model_free/seminar_qlearning.ipynb

Please, consider not using `%%writefile qlearning.py`, it's embarrassing.
In any case, you have to copy the code in the current version.

Not creating extra .py file

---

week06_policy_based/reinforce_lasagne.ipynb
week06_policy_based/reinforce_pytorch.ipynb
week06_policy_based/reinforce_tensorflow.ipynb

Fixes https://github.com/yandexdataschool/Practical_RL/issues/307.
The explanation in the notebook is pretty terrible, but this PR at least fixes a formula that is entirely wrong. A good fix would involve a summary of Sutton 13.2--13.3, but that's a lot more work.

[Week 6] Fix wrong objective formula in REINFORCE

---

week06_policy_based/atari_wrappers.py

Reverts yandexdataschool/Practical_RL#344

Revert "Fix unrandomness..." which did not fix the problem

---

week06_policy_based/a2c-optional.ipynb

* Update link to `xvfb` (and use version from our repo)
* Change 2-indentation to 4-indentation
* Fix some other spacing issues

[Week 6] Improve A2C notebook

---

week01_intro/crossentropy_method.ipynb
week01_intro/deep_crossentropy_method.ipynb
week01_intro/seminar_gym_interface.ipynb
week03_model_free/homework.ipynb
week03_model_free/seminar_qlearning.ipynb
week10_planning/seminar_MCTS.ipynb

#358 updates the initialization script. This PR updates the cells which refer to that script. Please note that the links in this PR are invalid until #358 is merged, hence two separate PRs.

Update Colab initialization code in some notebooks

---

week03_model_free/homework.ipynb

[Week 3] Fix Colab initialization in homework part 2

---

setup_colab.sh

Silence apt-get in Colab

---

week4_approx/practice_approx_qlearning.ipynb

There have been numerous complaints on the forum about this.
Will merge without review, it is trivial

[Week 4] Add TF global variable initializer

---

week10_planning/README.md
week10_planning/seminar_MCTS.ipynb

Updated pics, links and added some comments.

Spring20 week10 refactored

---

week6_outro/seq2seq/practice_tf.ipynb

Grader was accidentally deleted in #353.

[Week 6] Restore grader deleted during rebuild from master

---

week07_seq2seq/bonus_pytorch.ipynb

week7:bonus_pytroch import torch.nn.functional as F

---

week07_seq2seq/basic_model_torch.py

Comments for infer_mask and infer_length should be interchanged

week7: correct interchanged comments in basic_model_torch.py

---

week04_approx_rl/seminar_pytorch.ipynb
week04_approx_rl/seminar_tf.ipynb

[Week 4: CartPole] Clarify nonlinearities

---

week04_[recap]_deep_learning/seminar_pytorch.ipynb

This is a port of the corresponding change in the `coursera` branch. Fixed #306.

[Week 4: Recap PyTorch] Update Colab deps & remove __future__ import

---

week01_intro/primer_python_for_ml/recap_ml.ipynb

[recap ml] Cleanup

---

week04_[recap]_deep_learning/seminar_tensorflow.ipynb

https://colab.research.google.com/github/yandexdataschool/Practical_RL/blob/spring20-fix-recap-tf/week04_%5Brecap%5D_deep_learning/seminar_tensorflow.ipynb

[Week 4: Recap TF] Fix nonexistent variable (#192) & other cleanup

---

week4_approx/submit.py

[Week 4] Hotfix for missing Gym import

---

week02_value_based/seminar_vi.ipynb

Fixes https://github.com/yandexdataschool/Practical_RL/issues/179.
Tested in Colab and locally, it works.

[Week 2] Add assertion for incorrect handling of negative Q-values

---

week08_pomdp/homework_common_part2.ipynb

It was disabled a long time ago.

[Week 8] Remove mention of Gym leaderboard

---

week1_intro/crossentropy_method.ipynb
week1_intro/deep_crossentropy_method.ipynb
week1_intro/gym_interface.ipynb
week2_model_based/practice_vi.ipynb
week3_model_free/experience_replay.ipynb
week3_model_free/qlearning.ipynb
week3_model_free/sarsa.ipynb
week4_approx/dqn_atari.ipynb
week4_approx/dqn_atari_pytorch.ipynb
week4_approx/practice_approx_qlearning.ipynb
week4_approx/practice_approx_qlearning_pytorch.ipynb
week5_policy_based/practice_a3c.ipynb
week5_policy_based/practice_reinforce.ipynb
week5_policy_based/practice_reinforce_pytorch.ipynb
week6_outro/bandits.ipynb
week6_outro/practice_mcts.ipynb
week6_outro/seq2seq/practice_pytorch.ipynb
week6_outro/seq2seq/practice_tf.ipynb

Fixes #401. Too many complaints on the forum about that one.

s/<EMAIL>/'your.email@example.com', s/<TOKEN>/'YourAssignmentToken'

---

week1_intro/submit.py
week3_model_free/submit.py
week4_approx/submit.py
week5_policy_based/submit.py
week6_outro/seq2seq/submit.py

Submission functions now print what they send to the grader. Also refactored `submit.py` scripts quite heavily.

Print mean reward before submission

---

week02_value_based/mdp.py
week02_value_based/seminar_vi.ipynb

Passing `get_action_value` to `get_optimal_action_for_plot` via an import is error-prone (e.g. https://www.coursera.org/learn/practical-rl/discussions/all/threads/K61zm1OmQqetc5tTpsKnlA). This PR replaces the `%%writefile` and subsequent import with passing `get_action_value` via arguments.

[Week 2] Remove %%writefile

---

docker/Dockerfile
docker/deeplearning.yaml

dmittov/practical_rl
already updated

[docker] add python-graphviz to conda environment

---

week07_seq2seq/practice_tf.ipynb

Fixes TF in Colab, as discussed in https://www.coursera.org/learn/practical-rl/discussions/weeks/6/threads/gqt6tfWgEeqxrQ5g281r2Q .

Make TF 1.13.1 work in Colab again

---

week02_value_based/seminar_vi.ipynb
week04_approx_rl/homework_tf.ipynb
week09_policy_II/ppo.ipynb
week10_planning/seminar_MCTS.ipynb

I've also included a fix for the DQN Atari TF notebook, which apparently contains some leftovers from a conflict resolution.

Cleanup metadata in all notebooks

---

week04_approx_rl/homework_tf.ipynb

Week 4 approx rl. Modifications (mainly wrappers) from pytorch transferred to tf.

[Week 4: DQN Atari] Backport PyTorch modifications to TF

---

setup_colab.sh

Fixes https://github.com/yandexdataschool/Practical_RL/issues/479.

Add Atari ROM import to Colab setup script

---

week06_policy_based/a2c-optional.ipynb

Add note about target networks to A2C notebook

---

README.md

Minor in README

---

week09_policy_II/td3_and_sac/hw-continuous-control_pytorch.ipynb
week09_policy_II/td3_and_sac/logger.py

- всё на pytorch
- вычислительно по сложности 5-6 часов без GPU для преодоления указанного порога
- по сложности по идее проще, чем PPO
- TD3 работает лучше, чем SAC, возможно, в последнем можно подтюнить гиперпараметры
- прочекано пока лишь на двух студентах

Added HW on continuous control (TD3 or SAC)

---

week06_policy_based/reinforce_pytorch.ipynb

Install `classic_control` with `gym.wrapper` version

Install gym version with wrapper compatibility 

---

week05_explore/README.md

It is adding a new blog that summarises week 05 based on the provided materials for this week.

Adding new blog

---

week08_pomdp/practice_pytorch.ipynb

Fixed the error of `bash: ../xvfb: No such file or directory`, and now the videos are working on Colab and any server.

Downloading & Install `xvfb` for video game recording

---

week06_policy_based/a2c-optional.ipynb
week06_policy_based/atari_wrappers.py

There have been some [complaints](https://github.com/yandexdataschool/Practical_RL/pull/512) recently about the support for the A2C notebook in Colab. Here, I simplify the initialization of this notebook by removing the hardcoded versions for several packages.
I have tested that this notebook is still solvable end-to-end with the new setup.

[Week 06] Simplify Colab initialization and do some cleanup in the notebook

---

week01_intro/README.md
week01_intro/project_starter_evolution_strategies.ipynb

The link in README.md and the ipynb notebook was pointing to an unavailable resource, leading to a broken user experience.
This commit resolves the issue by updating the link to a valid URL, ensuring users can access the intended resource without any problems.
Changes Made:
- Fixed broken link in README.md
- Fixed broken link in ipynb notebook
Fixes #529

Fix: Update broken link in README.md and Notebook

---

week05_explore/week5.ipynb

- Support new interfaces of `reset()`  and `step()` functions
- Replace `bsuite` with `shimmy[bsuite]` (https://github.com/Farama-Foundation/Shimmy)
- Change `done` to `terminated or truncated `to iterate over env
- Change `done` to `terminated` to check whether bootstrap or not when game ends
- Fix bug in cross-entropy loss calculation in InverseDynamics

[Week05] Migrate to gymnasium

---

week08_pomdp/atari_util.py
week08_pomdp/env_pool.py
week08_pomdp/practice_pytorch.ipynb

- Support new interfaces in all files and notebooks
- Change `done` to `terminated or truncated` to iterate over env
- Change `done` to `terminated` to check whether bootstrap or not when game ends
- Update video recording code
- Replace custom `Flatten` and `to_one_hot` with torch `nn.Flatten` and `F.one_hot` respectively

[Week08] Migrate to gymnasium

---

week06_policy_based/a2c-optional.ipynb
week06_policy_based/atari_wrappers.py
week06_policy_based/env_batch.py
week06_policy_based/reinforce_pytorch.ipynb
week06_policy_based/runners.py

- Support new interfaces in all files and notebooks
- Change `done` to `terminated or truncated` to iterate over env
- Change `done` to `terminated` to check whether bootstrap or not when game ends
- Update video recording code
- Replace custom to_one_hot with F.one_hot in reinforce_pytorch.ipynb
- Update CartPole to v1 in reinforce_pytorch.ipynb
- Remove redundant imports from py files
- In atari_wrappers.py add `SwapImageAxes` wrapper to permute image axes and normalize pixels, replace `TFSummaries ` with `TensorboardSummaries` to log metrics in tensorboard, add auxiliary class `thunk_` (similar to [this](https://github.com/cydoroga/ftiad_rl_2021/blob/master/hw4/atari_wrappers.py) )

[Week06] migrate to gymnasium

---

docker/README.md

Change deprecated nvidia-docker repo to nvidia-container-toolkit.

Change deprecated github repo
